import {
  IconActivity,
  IconBrain,
  IconMoon,
  IconNote,
  IconRepeat,
  IconSalad,
  IconTargetArrow,
  type IconProps,
} from "@tabler/icons-react";
import type { ComponentType } from "react";

export interface NoteTemplate {
  id: string;
  label: string;
  description: string;
  icon: ComponentType<IconProps>;
  title?: string;
  tags?: string[];
  /** Seed markdown body. Empty for the blank note. */
  body: string;
}

export const NOTE_TEMPLATES: NoteTemplate[] = [
  {
    id: "blank",
    label: "Blank note",
    description: "Start from scratch",
    icon: IconNote,
    body: "",
  },
  {
    id: "habit-system",
    label: "Habit system",
    description: "Cue, routine, reward, and weekly tracking",
    icon: IconRepeat,
    title: "Habit System",
    tags: ["habits", "system"],
    body: [
      "**Identity:** I am the kind of person who ",
      "**Keystone habit:** ",
      "",
      "### Habit loop",
      "| Habit | Cue | Routine | Reward | Friction to remove |",
      "| --- | --- | --- | --- | --- |",
      "|  |  |  |  |  |",
      "|  |  |  |  |  |",
      "",
      "### Weekly tracker",
      "| Habit | Mon | Tue | Wed | Thu | Fri | Sat | Sun |",
      "| --- | --- | --- | --- | --- | --- | --- | --- |",
      "|  |  |  |  |  |  |  |  |",
      "|  |  |  |  |  |  |  |  |",
      "",
      "### Make it obvious",
      "- [ ] ",
      "### Make it easy",
      "- [ ] ",
      "### Make it satisfying",
      "- [ ] ",
    ].join("\n"),
  },
  {
    id: "diet-plan",
    label: "Diet plan",
    description: "Meals, calories, macros, and prep",
    icon: IconSalad,
    title: "Diet Plan",
    tags: ["diet", "health"],
    body: [
      "**Goal:** ",
      "**Daily calories:** ",
      "**Protein target:** ",
      "",
      "### Meal plan",
      "| Meal | Food | Calories | Protein | Prep notes |",
      "| --- | --- | --- | --- | --- |",
      "| Breakfast |  |  |  |  |",
      "| Lunch |  |  |  |  |",
      "| Snack |  |  |  |  |",
      "| Dinner |  |  |  |  |",
      "",
      "### Grocery list",
      "- [ ] ",
      "- [ ] ",
      "- [ ] ",
      "",
      "### Rules that make this easy",
      "- ",
    ].join("\n"),
  },
  {
    id: "daily-operating-system",
    label: "Daily OS",
    description: "Plan the day around energy and habits",
    icon: IconActivity,
    title: "Daily OS",
    tags: ["daily", "habits"],
    body: [
      "### Non-negotiables",
      "- [ ] Move",
      "- [ ] Eat to plan",
      "- [ ] Deep work",
      "- [ ] Sleep routine",
      "",
      "### Energy map",
      "| Time | Energy | Best use | Notes |",
      "| --- | --- | --- | --- |",
      "| Morning |  |  |  |",
      "| Afternoon |  |  |  |",
      "| Evening |  |  |  |",
      "",
      "### Today I will make progress by",
      "- ",
    ].join("\n"),
  },
  {
    id: "goal-breakdown",
    label: "Goal breakdown",
    description: "Turn a goal into systems and milestones",
    icon: IconTargetArrow,
    title: "Goal Breakdown",
    tags: ["goals", "system"],
    body: [
      "**Goal:** ",
      "**Why it matters:** ",
      "**Deadline:** ",
      "",
      "### System design",
      "| Outcome | Daily input | Weekly review metric | Current blocker |",
      "| --- | --- | --- | --- |",
      "|  |  |  |  |",
      "",
      "### Milestones",
      "| Milestone | Date | Done when |",
      "| --- | --- | --- |",
      "|  |  |  |",
      "|  |  |  |",
      "",
      "### Next actions",
      "- [ ] ",
      "- [ ] ",
      "- [ ] ",
    ].join("\n"),
  },
  {
    id: "sleep-recovery",
    label: "Sleep and recovery",
    description: "Track sleep quality, routines, and recovery",
    icon: IconMoon,
    title: "Sleep and Recovery",
    tags: ["sleep", "recovery"],
    body: [
      "**Target bedtime:** ",
      "**Wake time:** ",
      "",
      "### Wind-down routine",
      "- [ ] Screens off",
      "- [ ] Prepare tomorrow",
      "- [ ] Light stretch or breathwork",
      "",
      "### Recovery log",
      "| Date | Sleep hours | Quality | Training | Stress | Notes |",
      "| --- | --- | --- | --- | --- | --- |",
      "|  |  |  |  |  |  |",
      "|  |  |  |  |  |  |",
      "",
      "### What improves tomorrow",
      "- ",
    ].join("\n"),
  },
  {
    id: "mindset-reset",
    label: "Mindset reset",
    description: "Clear friction and choose the next response",
    icon: IconBrain,
    title: "Mindset Reset",
    tags: ["mindset", "reflection"],
    body: [
      "### What happened",
      "- ",
      "",
      "### Pattern check",
      "| Trigger | Thought | Feeling | Default action | Better response |",
      "| --- | --- | --- | --- | --- |",
      "|  |  |  |  |  |",
      "",
      "### Next small action",
      "- [ ] ",
    ].join("\n"),
  },
];
