"use client";

import { useEffect, useState } from "react";
import { AnimatePresence, m } from "framer-motion";
import { IconSparkles, IconX } from "@tabler/icons-react";
import { haptic } from "@/lib/haptics";
import { useAIEnabled } from "@/lib/ai/useAIEnabled";

/**
 * One-time notice that AI is on by default and where the off switch is.
 *
 * Shown once per device, then never again whichever button is pressed —
 * dismissing does not disable anything, it only stops the notice reappearing.
 *
 * The storage key is versioned. The previous notice said "set up local AI" and
 * pointed at a provider that needed installing; the default is now the
 * in-browser model, which needs nothing. Anyone who saw the old notice has not
 * been told any of that, so they should see this one.
 */
const AI_NOTICE_KEY = "planr_ai_default_notice_v2";

export default function AIOnboarding({ onOpenAISettings }: { onOpenAISettings: () => void }) {
  const [visible, setVisible] = useState(false);
  const aiEnabled = useAIEnabled();

  useEffect(() => {
    // Never announce a feature the user has already switched off.
    if (!aiEnabled) return;
    const t = setTimeout(() => {
      if (localStorage.getItem(AI_NOTICE_KEY) === null) setVisible(true);
    }, 2000);
    return () => clearTimeout(t);
  }, [aiEnabled]);

  function markSeen() {
    localStorage.setItem(AI_NOTICE_KEY, "true");
    setVisible(false);
  }

  function dismiss() {
    haptic("light");
    markSeen();
  }

  function handleOpenSettings() {
    haptic("light");
    markSeen();
    onOpenAISettings();
  }

  return (
    <AnimatePresence>
      {visible && (
        <>
          <m.div
            key="backdrop"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.25 }}
            className="fixed inset-0 z-[60] bg-black/30 dark:bg-black/50"
            onClick={dismiss}
          />

          <m.div
            key="sheet"
            role="dialog"
            aria-modal="true"
            aria-labelledby="ai-notice-title"
            initial={{ opacity: 0, y: "100%" }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: "100%" }}
            transition={{ type: "spring", stiffness: 320, damping: 32, mass: 0.9 }}
            className="fixed inset-x-0 bottom-0 z-[61] mx-auto max-w-lg"
            style={{ paddingBottom: "env(safe-area-inset-bottom)" }}
          >
            <div className="m-3 overflow-hidden rounded-2xl border border-neutral-200 bg-white dark:border-white/[0.08] dark:bg-neutral-900">
              <div className="flex justify-end px-5 pt-5">
                <button
                  type="button"
                  onClick={dismiss}
                  aria-label="Dismiss"
                  className="flex h-7 w-7 items-center justify-center rounded-full bg-neutral-100 text-neutral-500 hover:bg-neutral-200 dark:bg-white/[0.08] dark:text-neutral-400"
                >
                  <IconX size={14} strokeWidth={2} />
                </button>
              </div>

              <div className="flex justify-center px-5 pt-2 pb-5">
                <div className="flex h-20 w-20 items-center justify-center rounded-2xl border border-violet-500 bg-[#AD46FF]">
                  <IconSparkles size={36} strokeWidth={1.5} className="text-white" />
                </div>
              </div>

              <div className="px-6 pb-5 text-center">
                <h2 id="ai-notice-title" className="text-[22px] font-black leading-tight tracking-[-0.5px] text-neutral-900 dark:text-white">
                  AI is on, and it runs here
                </h2>
                <p className="mt-2 text-[14px] leading-snug text-neutral-500 dark:text-neutral-400">
                  Plans, tasks and your weekly read are generated by a small model
                  running inside this browser. No account, no API key, and nothing
                  you write leaves your device.
                </p>
                <p className="mt-3 text-[13px] leading-snug text-neutral-400 dark:text-neutral-500">
                  The first time you use it, it downloads a model once (around 460&nbsp;MB) and
                  then caches it. On a metered connection you may want to wait for Wi-Fi.
                  Don&apos;t want any of it? Turn AI off in Settings — every AI button
                  disappears.
                </p>
              </div>

              <div className="px-5 pb-6">
                <button
                  type="button"
                  onClick={dismiss}
                  className="flex w-full items-center justify-center gap-2.5 rounded-full bg-neutral-900 py-4 text-[16px] font-bold text-white transition-colors dark:bg-white dark:text-neutral-900"
                >
                  Got it
                </button>
                <button
                  type="button"
                  onClick={handleOpenSettings}
                  className="mt-3 w-full py-2 text-[13px] font-medium text-neutral-400 hover:text-neutral-600 dark:text-neutral-500 dark:hover:text-neutral-300"
                >
                  Open AI settings
                </button>
              </div>
            </div>
          </m.div>
        </>
      )}
    </AnimatePresence>
  );
}
